-- Namen aus Excel-Sheet 'Veranstaltungen' nachträglich eintragen
-- Einmalig ausführen

UPDATE veranstaltungen SET name = 'Sprint-Wettkampf CSV Marathon' WHERE kuerzel = '31.08.2025 Krefeld';
UPDATE veranstaltungen SET name = '44. Abendlauf' WHERE kuerzel = '29.08.2025 Hamminkeln';
UPDATE veranstaltungen SET name = 'NR Meisterschaften 10 km Straße' WHERE kuerzel = '24.08.2025 Eschweiler';
UPDATE veranstaltungen SET name = 'DM Masters Senioren' WHERE kuerzel = '24.08.2025 Gotha';
UPDATE veranstaltungen SET name = 'DM Masters Senioren' WHERE kuerzel = '23.08.2025 Gotha';
UPDATE veranstaltungen SET name = 'DM Masters Senioren' WHERE kuerzel = '22.08.2025 Gotha';
UPDATE veranstaltungen SET name = '3. Düsseldorfer Laufnacht' WHERE kuerzel = '08.08.2025 Düsseldorf';
UPDATE veranstaltungen SET name = '30. Rheinuferlauf' WHERE kuerzel = '26.07.2025 Duisburg';
UPDATE veranstaltungen SET name = 'Nordrhein/FLVW Meisterschaften 2025 Senioren und Seniorinnen' WHERE kuerzel = '06.07.2025 Wassenberg';
UPDATE veranstaltungen SET name = 'Nordrhein/FLVW Meisterschaften 2025 Senioren und Seniorinnen' WHERE kuerzel = '05.07.2025 Wassenberg';
UPDATE veranstaltungen SET name = 'Sparkassen Sportfest' WHERE kuerzel = '02.07.2025 Grefrath-Oedt';
UPDATE veranstaltungen SET name = 'Regionsmeisterschaften im Drei/Vierkampf U14 / 3.000m Lauf und Talentiade' WHERE kuerzel = '29.06.2025 Herzogenrath';
UPDATE veranstaltungen SET name = '42. Dr. Ernst van Aaken Gedächtnislauf' WHERE kuerzel = '27.06.2025 Waldniel';
UPDATE veranstaltungen SET name = 'Abend Sportfest' WHERE kuerzel = '27.06.2025 Aachen';
UPDATE veranstaltungen SET name = 'Nordrhein Meisterschaften 2025 U16 / U20 / M / F' WHERE kuerzel = '22.06.2025 Duisburg';
UPDATE veranstaltungen SET name = 'Nordrhein Meisterschaften 2025 U16 / U20 / M / F' WHERE kuerzel = '21.06.2025 Duisburg';
UPDATE veranstaltungen SET name = 'Open avondwedstrijd AV Unita' WHERE kuerzel = '20.06.2025 Sittard, NL';
UPDATE veranstaltungen SET name = '2. Stoppenberger Fronleichnamssportfest' WHERE kuerzel = '19.06.2025 Essen';
UPDATE veranstaltungen SET name = '51. Volkslauf' WHERE kuerzel = '19.06.2025 Schwafheim';
UPDATE veranstaltungen SET name = '32. Alpener Stadtlauf' WHERE kuerzel = '18.06.2025 Alpen';
UPDATE veranstaltungen SET name = 'Citylauf' WHERE kuerzel = '15.06.2025 Erkelenz';
UPDATE veranstaltungen SET name = 'Nordrhein Meisterschaften Jugend U14 / U18' WHERE kuerzel = '15.06.2025 Krefeld';
UPDATE veranstaltungen SET name = 'Nordrhein Meisterschaften Jugend U14 / U18' WHERE kuerzel = '14.06.2025 Krefeld';
UPDATE veranstaltungen SET name = '9. Citylauf' WHERE kuerzel = '13.06.2025 Grevenbroich';
UPDATE veranstaltungen SET name = '38. Großes LGM Pfingstsportfest' WHERE kuerzel = '09.06.2025 Mönchengladbach';
UPDATE veranstaltungen SET name = 'Sprintpokal- und Mittelstreckenabend' WHERE kuerzel = '04.06.2025 Grefrath-Oedt';
UPDATE veranstaltungen SET name = '38. Brunnenlauf' WHERE kuerzel = '28.05.2025 Sonsbeck';
UPDATE veranstaltungen SET name = 'Region Mitte Einzelmeisterschaften MJ/WJ U20 & M/F' WHERE kuerzel = '18.05.2025 Siegburg';
UPDATE veranstaltungen SET name = '7. Ra(h)ser Run' WHERE kuerzel = '18.05.2025 Viersen';
UPDATE veranstaltungen SET name = '42. Rhein-Ruhr Marathon' WHERE kuerzel = '18.05.2025 Duisburg';
UPDATE veranstaltungen SET name = 'Regionsmeisterschaften U16 & Langstrecke U14' WHERE kuerzel = '17.05.2025 Mönchengladbach';
UPDATE veranstaltungen SET name = 'Citylauf' WHERE kuerzel = '10.05.2025 Geldern';
UPDATE veranstaltungen SET name = 'Regionsmeisterschaften Südwest' WHERE kuerzel = '10.05.2025 Aachen';
UPDATE veranstaltungen SET name = 'Regionsmeisterschaften U14/U18 & Langstrecke U16' WHERE kuerzel = '10.05.2025 Korschenbroich';
UPDATE veranstaltungen SET name = 'Bahneröffnung' WHERE kuerzel = '07.05.2025 Grefrath-Oedt';
UPDATE veranstaltungen SET name = 'Novesia Sprintertag' WHERE kuerzel = '04.05.2025 Neuss';
UPDATE veranstaltungen SET name = 'Bocholter Citylauf' WHERE kuerzel = '03.05.2025 Bocholt';
UPDATE veranstaltungen SET name = 'Osterrather Mailauf' WHERE kuerzel = '01.05.2025 Meerbusch';
UPDATE veranstaltungen SET name = 'Marathon' WHERE kuerzel = '27.04.2025 Düsseldorf';
UPDATE veranstaltungen SET name = 'Apfelblütenlauf' WHERE kuerzel = '27.04.2025 Tönisvorst';
UPDATE veranstaltungen SET name = 'Marathon' WHERE kuerzel = '13.04.2025 Rotterdam';
UPDATE veranstaltungen SET name = 'Halbmarathon' WHERE kuerzel = '06.04.2025 Bonn';
UPDATE veranstaltungen SET name = 'Citylauf' WHERE kuerzel = '06.04.2025 Korschenbroich';
UPDATE veranstaltungen SET name = 'Venloop' WHERE kuerzel = '30.03.2025 Venlo';
UPDATE veranstaltungen SET name = 'Winterlauf-Serie (3/3)' WHERE kuerzel = '29.03.2025 Duisburg';
UPDATE veranstaltungen SET name = 'Winterlauf-Serie (2/3)' WHERE kuerzel = '08.03.2025 Duisburg';
UPDATE veranstaltungen SET name = 'DM Halle Masters' WHERE kuerzel = '02.03.2025 Frankfurt';
UPDATE veranstaltungen SET name = 'DM Halle Masters' WHERE kuerzel = '01.03.2025 Frankfurt';
UPDATE veranstaltungen SET name = '42. Karnevalslauf MG Hardt' WHERE kuerzel = '01.03.2025 MG-Hardt';
UPDATE veranstaltungen SET name = 'LVN Hallenmeisterschaften U14/U16' WHERE kuerzel = '23.02.2025 Düsseldorf-Halle';
UPDATE veranstaltungen SET name = 'LVN Hallenmeisterschaften U14/U16' WHERE kuerzel = '22.02.2025 Düsseldorf-Halle';
UPDATE veranstaltungen SET name = 'LVN Hallenmeisterschaften Masters' WHERE kuerzel = '16.02.2025 Düsseldorf-Halle';
UPDATE veranstaltungen SET name = 'Winterlauf-Serie (1/3)' WHERE kuerzel = '08.02.2025 Duisburg';
UPDATE veranstaltungen SET name = 'Halbmarathon Murcia' WHERE kuerzel = '02.02.2025 Murcia';
UPDATE veranstaltungen SET name = 'Regionshallenmeisterschaften Region Mitte U14/U16' WHERE kuerzel = '18.01.2025 Düsseldorf';
UPDATE veranstaltungen SET name = 'Regionshallenmeisterschaften, Region Mitte' WHERE kuerzel = '12.01.2025 Düsseldorf';
UPDATE veranstaltungen SET name = 'Regionshallenmeisterschaften, Region Mitte' WHERE kuerzel = '11.01.2025 Düsseldorf';
UPDATE veranstaltungen SET name = '3. Hülskens Marathon' WHERE kuerzel = '05.01.2025 Wesel';
UPDATE veranstaltungen SET name = '35. Sylvesterlauf' WHERE kuerzel = '31.12.2024 Goch Pfalzdorf';
UPDATE veranstaltungen SET name = '18. Hallensportfest Bayer Uerdingen' WHERE kuerzel = '14.12.2024 Düsseldorf';
UPDATE veranstaltungen SET name = 'Nikolauslauf' WHERE kuerzel = '07.12.2024 Dülmen';
UPDATE veranstaltungen SET name = '14. Düsseldorfer Advent-Indoor-Meeting' WHERE kuerzel = '07.12.2024 Düsseldorf';
UPDATE veranstaltungen SET name = '33. TUSEM Blumensaat-Lauf' WHERE kuerzel = '23.11.2024 Essen';
UPDATE veranstaltungen SET name = '33. Schülerhallensportfest' WHERE kuerzel = '16.11.2024 Düsseldorf';
UPDATE veranstaltungen SET name = '51. Neusser Erftlauf' WHERE kuerzel = '16.11.2024 Neuss';
UPDATE veranstaltungen SET name = 'Rhein-City-Run' WHERE kuerzel = '27.10.2024 Düsseldorf';
UPDATE veranstaltungen SET name = 'Kölnmarathon' WHERE kuerzel = '06.10.2024 Köln';
UPDATE veranstaltungen SET name = 'Citylauf; NR Meisterschaften' WHERE kuerzel = '29.09.2024 Eschweiler';
UPDATE veranstaltungen SET name = '50. BMW Berlin Marathon' WHERE kuerzel = '29.09.2024 Berlin';
UPDATE veranstaltungen SET name = '9. Welterbelauf Zollverein' WHERE kuerzel = '14.09.2024 Essen';
UPDATE veranstaltungen SET name = 'Stadtlauf Jüchen' WHERE kuerzel = '08.09.2024 Jüchen';
UPDATE veranstaltungen SET name = '9. Stadtwerke Kamp-Lintfort Herbstsportfest mit LVN-Talentiade' WHERE kuerzel = '08.09.2024 Kamp-Lintfort';
UPDATE veranstaltungen SET name = '13. Kohlscheider Sprintertag' WHERE kuerzel = '04.09.2024 Herzogenrath';
UPDATE veranstaltungen SET name = 'do it fast Sommer-Edition' WHERE kuerzel = '25.08.2024 Dortmund';
UPDATE veranstaltungen SET name = '19. Gladbecker Sparkassenlauf' WHERE kuerzel = '25.08.2024 Gladbeck';
UPDATE veranstaltungen SET name = '25. Masters Weltmeisterschaften' WHERE kuerzel = '24.08.2024 Göteborg';
UPDATE veranstaltungen SET name = '25. Masters Weltmeisterschaften' WHERE kuerzel = '23.08.2024 Göteborg';
UPDATE veranstaltungen SET name = '25. Masters Weltmeisterschaften' WHERE kuerzel = '22.08.2024 Göteborg';
UPDATE veranstaltungen SET name = '25. Masters Weltmeisterschaften' WHERE kuerzel = '19.08.2024 Göteborg';
UPDATE veranstaltungen SET name = '25. Masters Weltmeisterschaften' WHERE kuerzel = '17.08.2024 Göteborg';
UPDATE veranstaltungen SET name = '2. Düsseldorfer Laufnacht' WHERE kuerzel = '16.08.2024 Düsseldorf';
UPDATE veranstaltungen SET name = '19. Drevenacker Abendlauf' WHERE kuerzel = '05.07.2024 Hünxe';
UPDATE veranstaltungen SET name = 'LVN NORDRHEIN JUGENDMEISTERSCHAFTEN 2024 U16/U20' WHERE kuerzel = '30.06.2024 Troisdorf';
UPDATE veranstaltungen SET name = 'LVN NORDRHEIN JUGENDMEISTERSCHAFTEN 2024 U16/U20' WHERE kuerzel = '29.06.2024 Troisdorf';
UPDATE veranstaltungen SET name = '21. Halderner Volkslauf "Rund um\'s Reeser Meer"' WHERE kuerzel = '23.06.2024 Rees';
UPDATE veranstaltungen SET name = '109. Großes Bergfest' WHERE kuerzel = '23.06.2024 Viersen-Süchteln';
UPDATE veranstaltungen SET name = '41. Dr. Ernst van Aaken Gedächtnislauf' WHERE kuerzel = '21.06.2024 Waldniel';
UPDATE veranstaltungen SET name = 'Sparkassen Sportfest' WHERE kuerzel = '19.06.2024 Grefrath-Oedt';
UPDATE veranstaltungen SET name = 'Metropol Marathon Fürth-Nürnberg' WHERE kuerzel = '16.06.2024 Fürth';
UPDATE veranstaltungen SET name = 'DM Masters Senioren' WHERE kuerzel = '16.06.2024 Erding';
UPDATE veranstaltungen SET name = 'LV Nordrhein Jugendmeisterschaften U14/U18' WHERE kuerzel = '15.06.2024 Krefeld';
UPDATE veranstaltungen SET name = 'DM Masters Senioren' WHERE kuerzel = '15.06.2024 Erding';
UPDATE veranstaltungen SET name = 'DM Masters Senioren' WHERE kuerzel = '14.06.2024 Erding';
UPDATE veranstaltungen SET name = 'City Lauf' WHERE kuerzel = '14.06.2024 Grevenbroich';
UPDATE veranstaltungen SET name = 'Nordrhein Meisterschaften Senioren' WHERE kuerzel = '01.06.2024 Mönchengladbach';
UPDATE veranstaltungen SET name = 'Sport Palast Cup' WHERE kuerzel = '30.05.2024 Kamp-Lintfort';
UPDATE veranstaltungen SET name = 'Ra(h)ser Run' WHERE kuerzel = '26.05.2024 Viersen';
UPDATE veranstaltungen SET name = 'Regionseinzelmeisterschaften SüdWest' WHERE kuerzel = '25.05.2024 Euskirchen';
UPDATE veranstaltungen SET name = 'Pfingstsportfest' WHERE kuerzel = '20.05.2024 Mönchengladbach';
UPDATE veranstaltungen SET name = 'Sprintpokal- und Mittelstreckenabend' WHERE kuerzel = '15.05.2024 Grefrath-Oedt';
UPDATE veranstaltungen SET name = 'Brückenlauf' WHERE kuerzel = '12.05.2024 Düsseldorf';
UPDATE veranstaltungen SET name = 'Regionsmeisterschaften Region Mitte U16-M/F' WHERE kuerzel = '12.05.2024 Dormagen';
UPDATE veranstaltungen SET name = 'Regionsmeisterschaften Region Mitte U16-M/F' WHERE kuerzel = '11.05.2024 Dormagen';
UPDATE veranstaltungen SET name = 'Brunnenlauf' WHERE kuerzel = '08.05.2024 Sonsbeck';
UPDATE veranstaltungen SET name = '41. Rhein-Ruhr Marathon' WHERE kuerzel = '05.05.2024 Duisburg';
UPDATE veranstaltungen SET name = 'Regionseinzelmeisterschaften U14' WHERE kuerzel = '04.05.2024 Neuss';
UPDATE veranstaltungen SET name = 'City Lauf' WHERE kuerzel = '04.05.2024 Bocholt';
UPDATE veranstaltungen SET name = 'Sprint in den Mai' WHERE kuerzel = '28.04.2024 Viersen-Süchteln';
UPDATE veranstaltungen SET name = 'Hamburg Marathon' WHERE kuerzel = '28.04.2024 Hamburg';
UPDATE veranstaltungen SET name = 'Apfelblütenlauf' WHERE kuerzel = '28.04.2024 Tönisvorst';
UPDATE veranstaltungen SET name = 'Enschede Marathon' WHERE kuerzel = '21.04.2024 Enschede';
UPDATE veranstaltungen SET name = 'City Lauf' WHERE kuerzel = '21.04.2024 Korschenbroich';
UPDATE veranstaltungen SET name = 'Bahneröffnung TuS Oedt' WHERE kuerzel = '17.04.2024 Grefrath-Oedt';
UPDATE veranstaltungen SET name = 'NN Marathon' WHERE kuerzel = '14.04.2024 Rotterdam';
UPDATE veranstaltungen SET name = 'Deutsche Post Marathon' WHERE kuerzel = '14.04.2024 Bonn';
UPDATE veranstaltungen SET name = 'Generali Halbmarathon' WHERE kuerzel = '07.04.2024 Berlin';
UPDATE veranstaltungen SET name = 'Venloop' WHERE kuerzel = '24.03.2024 Venlo';
UPDATE veranstaltungen SET name = 'Winterlauf-Serie (3/3)' WHERE kuerzel = '23.03.2024 Duisburg';
UPDATE veranstaltungen SET name = 'Halbmarathon' WHERE kuerzel = '17.03.2024 Lissabon';
UPDATE veranstaltungen SET name = 'Stadtwerke Dinslaken Energy Run' WHERE kuerzel = '17.03.2024 Dinslaken';
UPDATE veranstaltungen SET name = '51. Schülerwaldlauf Forstwald' WHERE kuerzel = '17.03.2024 Krefeld';
UPDATE veranstaltungen SET name = 'Deutsche Meisterschaften Straßenlauf 10 km' WHERE kuerzel = '03.03.2024 Leverkusen';
UPDATE veranstaltungen SET name = 'Deutsche Seniorenmeisterschaften Halle (2/2)' WHERE kuerzel = '03.03.2024 Dortmund';
UPDATE veranstaltungen SET name = 'Deutsche Seniorenmeisterschaften Halle (1/2)' WHERE kuerzel = '02.03.2024 Dortmund';
UPDATE veranstaltungen SET name = 'LVN Hallenmeisterschaften U14' WHERE kuerzel = '02.03.2024 Düsseldorf-Halle';
UPDATE veranstaltungen SET name = 'Winterlauf-Serie (2/3)' WHERE kuerzel = '24.02.2024 Duisburg';
UPDATE veranstaltungen SET name = 'Nordrhein Meisterschaften LVN Halle' WHERE kuerzel = '18.02.2024 Düsseldorf-Halle';
UPDATE veranstaltungen SET name = 'Winterlauf-Serie (3/3)' WHERE kuerzel = '18.02.2024 Hilden';
UPDATE veranstaltungen SET name = 'Karnevalslauf' WHERE kuerzel = '10.02.2024 MG-Hardt';
UPDATE veranstaltungen SET name = 'Winterlauf-Serie (2/3)' WHERE kuerzel = '04.02.2024 Hilden';
UPDATE veranstaltungen SET name = 'do it fast Winter-Edition' WHERE kuerzel = '04.02.2024 Dortmund';
UPDATE veranstaltungen SET name = 'ISTAF Indoor Talents Cup U 14' WHERE kuerzel = '04.02.2024 Düsseldorf-Halle';
UPDATE veranstaltungen SET name = 'REGIONSHALLENMEISTERSCHAFTEN U14 MIT REGIONSWETTKAMPF U 12' WHERE kuerzel = '28.01.2024 Düsseldorf-Halle';
UPDATE veranstaltungen SET name = 'Winterlauf-Serie (1/3)' WHERE kuerzel = '27.01.2024 Duisburg';
UPDATE veranstaltungen SET name = 'Winterlauf-Serie (1/3)' WHERE kuerzel = '21.01.2024 Hilden';
UPDATE veranstaltungen SET name = 'Rund um den Haltener See' WHERE kuerzel = '20.01.2024 Haltern';
UPDATE veranstaltungen SET name = 'Waldlauf' WHERE kuerzel = '20.01.2024 Hinsbeck';
UPDATE veranstaltungen SET name = 'Regionshallenmeisterschaften M/F der Region Mitte' WHERE kuerzel = '14.01.2024 Düsseldorf-Halle';
UPDATE veranstaltungen SET name = 'Regionshallenmeisterschaften U16-U20 der Region Mitte' WHERE kuerzel = '13.01.2024 Düsseldorf-Halle';
UPDATE veranstaltungen SET name = 'Hülskens-Marathon' WHERE kuerzel = '07.01.2024 Wesel';
UPDATE veranstaltungen SET name = 'Neujahrslauf' WHERE kuerzel = '07.01.2024 Ratingen';
UPDATE veranstaltungen SET name = 'Silvesterlauf' WHERE kuerzel = '31.12.2023 Bocholt';
UPDATE veranstaltungen SET name = '32. Sylvesterlauf Pfalzdorf' WHERE kuerzel = '31.12.2023 Goch';
UPDATE veranstaltungen SET name = '42. Silvesterlauf' WHERE kuerzel = '31.12.2023 Werl-Soest';
UPDATE veranstaltungen SET name = 'Advent Indoor Meeting' WHERE kuerzel = '16.12.2023 Düsseldorf-Halle';
UPDATE veranstaltungen SET name = 'Hallensportfest Bayer Uerdingen' WHERE kuerzel = '09.12.2023 Düsseldorf-Halle';
UPDATE veranstaltungen SET name = 'Bertlicher Straßenläufe' WHERE kuerzel = '03.12.2023 Bertlich';
UPDATE veranstaltungen SET name = 'Erftlauf' WHERE kuerzel = '18.11.2023 Neuss';
UPDATE veranstaltungen SET name = 'Blumensaatlauf' WHERE kuerzel = '18.11.2023 Essen';
UPDATE veranstaltungen SET name = 'Schülerhallensportfest' WHERE kuerzel = '18.11.2023 Düsseldorf-Halle';
UPDATE veranstaltungen SET name = 'Martinslauf Unterbacher See' WHERE kuerzel = '12.11.2023 Düsseldorf';
UPDATE veranstaltungen SET name = 'Herbstwaldlauf' WHERE kuerzel = '05.11.2023 Bocholt';
UPDATE veranstaltungen SET name = 'Halloween Run' WHERE kuerzel = '31.10.2023 Duisburg';
UPDATE veranstaltungen SET name = 'Rhein-City-Run' WHERE kuerzel = '22.10.2023 Düsseldorf';
UPDATE veranstaltungen SET name = 'Nordrhein Meisterschaften LVN Straße' WHERE kuerzel = '15.10.2023 Refrath';
UPDATE veranstaltungen SET name = 'Volkskauf und Halbmarathon' WHERE kuerzel = '15.10.2023 Geilenkirchen';
UPDATE veranstaltungen SET name = 'Herbstwaldlauf' WHERE kuerzel = '14.10.2023 Viersen';
UPDATE veranstaltungen SET name = 'KustMarathon' WHERE kuerzel = '08.10.2023 Zoutelande';
UPDATE veranstaltungen SET name = 'Klosterlauf' WHERE kuerzel = '03.10.2023 Kamp-Lintfort';
UPDATE veranstaltungen SET name = 'Kölnmarathon' WHERE kuerzel = '01.10.2023 Köln';
UPDATE veranstaltungen SET name = 'BMW Berlin Marathon' WHERE kuerzel = '24.09.2023 Berlin';
UPDATE veranstaltungen SET name = 'Lichterlauf' WHERE kuerzel = '16.09.2023 Duisburg';
UPDATE veranstaltungen SET name = 'Citylauf' WHERE kuerzel = '15.09.2023 Xanten';
UPDATE veranstaltungen SET name = 'Welterbelauf Zollverein' WHERE kuerzel = '09.09.2023 Essen';
UPDATE veranstaltungen SET name = 'Stadtlauf' WHERE kuerzel = '03.09.2023 Wachtendonk';
UPDATE veranstaltungen SET name = 'Firmenlauf "Rund und Fun"' WHERE kuerzel = '30.08.2023 Krefeld';
UPDATE veranstaltungen SET name = 'Lank läuft' WHERE kuerzel = '20.08.2023 Meerbusch';
UPDATE veranstaltungen SET name = 'NRW Meisterschaften 10 km Straße' WHERE kuerzel = '20.08.2023 Dortmund';
UPDATE veranstaltungen SET name = '45. Monschau Marathon' WHERE kuerzel = '13.08.2023 Monschau';
UPDATE veranstaltungen SET name = 'Deutsche Seniorenmeisterschaften (2/2)' WHERE kuerzel = '13.08.2023 Mönchengladbach';
UPDATE veranstaltungen SET name = 'Deutsche Seniorenmeisterschaften (1/2)' WHERE kuerzel = '12.08.2023 Mönchengladbach';
UPDATE veranstaltungen SET name = 'Rheinufer Lauf' WHERE kuerzel = '29.07.2023 Duisburg';
UPDATE veranstaltungen SET name = 'Abendlauf' WHERE kuerzel = '07.07.2023 Drevenacker';
UPDATE veranstaltungen SET name = '20. Haldener Volkslauf' WHERE kuerzel = '25.06.2023 Haldern';
UPDATE veranstaltungen SET name = 'Bergfest' WHERE kuerzel = '18.06.2023 Viersen-Süchteln';
UPDATE veranstaltungen SET name = 'FLWL VW (Westfälische) Seniorenmeisterschaften' WHERE kuerzel = '17.06.2023 Reken';
UPDATE veranstaltungen SET name = 'Sommersportfest' WHERE kuerzel = '14.06.2023 Grefrath-Oedt';
UPDATE veranstaltungen SET name = 'Rhein-Ruhr-Marathon' WHERE kuerzel = '11.06.2023 Duisburg';
UPDATE veranstaltungen SET name = 'Norderstedter Stadtlauf' WHERE kuerzel = '11.06.2023 Norderstedt';
UPDATE veranstaltungen SET name = 'Stadtlauf' WHERE kuerzel = '07.06.2023 Alpen';
UPDATE veranstaltungen SET name = 'Talentiade U12 LVN' WHERE kuerzel = '04.06.2023 Krefeld';
UPDATE veranstaltungen SET name = 'Nordrhein Meisterschaften' WHERE kuerzel = '03.06.2023 Mönchengladbach';
UPDATE veranstaltungen SET name = 'Sommernachtslauf' WHERE kuerzel = '03.06.2023 Neuss';
UPDATE veranstaltungen SET name = 'Citylauf' WHERE kuerzel = '03.06.2023 Grevenbroich';
UPDATE veranstaltungen SET name = 'Pfingstsportfest' WHERE kuerzel = '29.05.2023 Mönchengladbach';
UPDATE veranstaltungen SET name = 'Sprintpokal- und Mittelstreckenabend' WHERE kuerzel = '24.05.2023 Grefrath-Oedt';
UPDATE veranstaltungen SET name = 'Rahser-Run' WHERE kuerzel = '21.05.2023 Viersen';
UPDATE veranstaltungen SET name = 'Himmelfahrts Sportfest' WHERE kuerzel = '18.05.2023 Essen';
UPDATE veranstaltungen SET name = 'Brunnenlauf' WHERE kuerzel = '17.05.2023 Sonsbeck';
UPDATE veranstaltungen SET name = 'Regionsmeisterschaften U16/U18/M/F Region Mitte' WHERE kuerzel = '14.05.2023 Krefeld-Uerdingen';
UPDATE veranstaltungen SET name = 'Regionsmeisterschaften SüdWest' WHERE kuerzel = '07.05.2023 Euskirchen';
UPDATE veranstaltungen SET name = 'Citylauf' WHERE kuerzel = '06.05.2023 Bocholt';
UPDATE veranstaltungen SET name = 'Mailauf' WHERE kuerzel = '01.05.2023 Meerbusch-Osterrath';
UPDATE veranstaltungen SET name = 'Sprint in den Mai' WHERE kuerzel = '30.04.2023 Viersen-Süchteln';
UPDATE veranstaltungen SET name = 'Schloßparklauf' WHERE kuerzel = '29.04.2023 Moers';
UPDATE veranstaltungen SET name = 'Marathon' WHERE kuerzel = '23.04.2023 Bonn';
UPDATE veranstaltungen SET name = 'NRW Meisterschaften' WHERE kuerzel = '22.04.2023 Dortmund';
UPDATE veranstaltungen SET name = 'Bahneröffnung' WHERE kuerzel = '19.04.2023 Grefrath-Oedt';
UPDATE veranstaltungen SET name = 'Apfelblütenlauf' WHERE kuerzel = '16.04.2023 Tönisvorst';
UPDATE veranstaltungen SET name = 'Freiburg Marathon' WHERE kuerzel = '26.03.2023 Freiburg';
UPDATE veranstaltungen SET name = 'Karnevalslauf' WHERE kuerzel = '18.02.2023 MG-Hardt';
UPDATE veranstaltungen SET name = 'Neusser Erftlauf' WHERE kuerzel = '19.11.2022 Neuss';
UPDATE veranstaltungen SET name = 'Kölnmarathon' WHERE kuerzel = '02.10.2022 Köln';
UPDATE veranstaltungen SET name = 'Deutsche Meisterschaften' WHERE kuerzel = '17.09.2022 Erding';
UPDATE veranstaltungen SET name = 'Stadtlauf' WHERE kuerzel = '04.09.2022 Wachtendonk';
UPDATE veranstaltungen SET name = 'Sommersportfest' WHERE kuerzel = '21.08.2022 Aachen';
UPDATE veranstaltungen SET name = 'Nordrhein Meisterschaften' WHERE kuerzel = '02.07.2022 Euskirchen';
UPDATE veranstaltungen SET name = 'Bergfest' WHERE kuerzel = '26.06.2022 Viersen-Süchteln';
UPDATE veranstaltungen SET name = 'TuS Oedt Sprint- und Mittelstreckenabend' WHERE kuerzel = '15.06.2022 Grefrath-Oedt';
UPDATE veranstaltungen SET name = 'Rhein-Ruhr-Marathon' WHERE kuerzel = '12.06.2022 Duisburg';
UPDATE veranstaltungen SET name = 'Rahser-Run' WHERE kuerzel = '22.05.2022 Viersen';
UPDATE veranstaltungen SET name = 'Bocholter Citylauf' WHERE kuerzel = '07.05.2022 Bocholt';
UPDATE veranstaltungen SET name = 'TuS Oedt Bahneröffnung' WHERE kuerzel = '04.05.2022 Grefrath-Oedt';
UPDATE veranstaltungen SET name = 'Enschede Marathon' WHERE kuerzel = '24.04.2022 Enschede';
UPDATE veranstaltungen SET name = 'Bunert Solo Run' WHERE kuerzel = '27.03.2022 Kerken';
UPDATE veranstaltungen SET name = 'NRW Meisterschaften' WHERE kuerzel = '19.03.2022 Münster';
UPDATE veranstaltungen SET name = 'Straßenlauf rund um das Bayer-Kreuz' WHERE kuerzel = '06.03.2022 Leverkusen';
UPDATE veranstaltungen SET name = 'NRW Meisterschaften' WHERE kuerzel = '05.03.2022 Düsseldorf';
UPDATE veranstaltungen SET name = 'Offene Regionshallenmeisterschaften' WHERE kuerzel = '26.02.2022 Düsseldorf';
UPDATE veranstaltungen SET name = 'Advent Indoor Meeting' WHERE kuerzel = '12.12.2021 Düsseldorf';
UPDATE veranstaltungen SET name = 'Erftlauf' WHERE kuerzel = '20.11.2021 Neuss';
UPDATE veranstaltungen SET name = 'Blumensaatlauf' WHERE kuerzel = '20.11.2021 Essen';
UPDATE veranstaltungen SET name = 'Drei-Brücken-Lauf' WHERE kuerzel = '10.10.2021 Bonn';
UPDATE veranstaltungen SET name = 'Herbstwaldlauf' WHERE kuerzel = '09.10.2021 Viersen';
UPDATE veranstaltungen SET name = 'Runway Race' WHERE kuerzel = '02.10.2021 Mönchengladbach';
UPDATE veranstaltungen SET name = 'Schloßparklauf' WHERE kuerzel = '02.10.2021 Moers';
UPDATE veranstaltungen SET name = 'BMW Berlin Marathon' WHERE kuerzel = '26.09.2021 Berlin';
UPDATE veranstaltungen SET name = 'hep Triathlon' WHERE kuerzel = '19.09.2021 Heilbronn';
UPDATE veranstaltungen SET name = 'Bunerts Lichterlauf' WHERE kuerzel = '18.09.2021 Duisburg';
UPDATE veranstaltungen SET name = 'Deutsche Seniorenmeisterschaften (1/2)' WHERE kuerzel = '10.09.2021 Baunatal';
UPDATE veranstaltungen SET name = 'Burgwald Märchen Marathon' WHERE kuerzel = '29.08.2021 Rauschenberg';
UPDATE veranstaltungen SET name = 'Lank läuft' WHERE kuerzel = '29.08.2021 Meerbusch';
UPDATE veranstaltungen SET name = 'Krefelder Kulturlauf' WHERE kuerzel = '29.08.2021 Krefeld';
UPDATE veranstaltungen SET name = 'Kölner Halbmarathon' WHERE kuerzel = '29.08.2021 Köln';
UPDATE veranstaltungen SET name = 'Ironman 70.3' WHERE kuerzel = '29.08.2021 Duisburg';
UPDATE veranstaltungen SET name = 'Pokallauf Möhnesee' WHERE kuerzel = '28.08.2021 Möhnesee';
UPDATE veranstaltungen SET name = 'Nordrhein Meisterschaften' WHERE kuerzel = '28.08.2021 Düsseldorf';
UPDATE veranstaltungen SET name = 'Offene Münsterlandmeisterschaften' WHERE kuerzel = '21.08.2021 Lüdinghausen';
UPDATE veranstaltungen SET name = 'Tus Oedt Bahnwettkampf' WHERE kuerzel = '11.06.2021 Grefrath-Oedt';
UPDATE veranstaltungen SET name = 'Winterlauf-Serie (3/3)' WHERE kuerzel = '11.04.2021 Duisburg (virtuell)';
UPDATE veranstaltungen SET name = 'Winterlauf-Serie (2/3)' WHERE kuerzel = '14.03.2021 Duisburg (virtuell)';
UPDATE veranstaltungen SET name = 'Winterlauf-Serie (1/3)' WHERE kuerzel = '21.02.2021 Duisburg (virtuell)';
UPDATE veranstaltungen SET name = 'Herbstwaldlauf' WHERE kuerzel = '10.10.2020 Viersen';
UPDATE veranstaltungen SET name = 'Bunerts Lichterlauf' WHERE kuerzel = '19.09.2020 Duisburg';
UPDATE veranstaltungen SET name = 'Karnevalslauf' WHERE kuerzel = '22.02.2020 MG-Hardt';
UPDATE veranstaltungen SET name = 'Hallenmeisterschaft LVN Region Mitte' WHERE kuerzel = '25.01.2020 Düsseldorf';
UPDATE veranstaltungen SET name = 'Waldlauf' WHERE kuerzel = '18.01.2020 Hinsbeck';
UPDATE veranstaltungen SET name = 'Winterlaufserie (1/3)' WHERE kuerzel = '18.01.2020 Duisburg';
UPDATE veranstaltungen SET name = 'NRW-Hallenmeisterschaft' WHERE kuerzel = '12.01.2020 Düsseldorf';
UPDATE veranstaltungen SET name = 'Hülskens-Marathon' WHERE kuerzel = '05.01.2020 Wesel';
UPDATE veranstaltungen SET name = 'Hallensportfest' WHERE kuerzel = '05.01.2020 Dortmund';
UPDATE veranstaltungen SET name = 'Silvesterlauf' WHERE kuerzel = '31.12.2019 Bocholt';
UPDATE veranstaltungen SET name = 'Blumensaatlauf' WHERE kuerzel = '23.11.2019 Essen';
UPDATE veranstaltungen SET name = 'Erftlauf' WHERE kuerzel = '16.11.2019 Neuss';
UPDATE veranstaltungen SET name = 'Röntgenlauf' WHERE kuerzel = '27.10.2019 Remscheid';
UPDATE veranstaltungen SET name = 'Jungbornparklauf' WHERE kuerzel = '27.10.2019 Moers';
UPDATE veranstaltungen SET name = 'TCS Marathon' WHERE kuerzel = '20.10.2019 Amsterdam';
UPDATE veranstaltungen SET name = 'Rhein-Energie-Marathon' WHERE kuerzel = '13.10.2019 Köln';
UPDATE veranstaltungen SET name = 'Waldlauf' WHERE kuerzel = '12.10.2019 Viersen';
UPDATE veranstaltungen SET name = 'Waldlauf' WHERE kuerzel = '28.09.2019 Korschenbroich';
UPDATE veranstaltungen SET name = 'Weezer Staffellauf' WHERE kuerzel = '21.09.2019 Weeze';
UPDATE veranstaltungen SET name = 'Deutsche Meisterschaft Straßenlauf' WHERE kuerzel = '15.09.2019 Siegburg';
UPDATE veranstaltungen SET name = 'HM Fühlinger See' WHERE kuerzel = '15.09.2019 Köln';
UPDATE veranstaltungen SET name = 'Bahnlaufserie' WHERE kuerzel = '11.09.2019 Düsseldorf';
UPDATE veranstaltungen SET name = 'NEW-Volksbad-Lauf' WHERE kuerzel = '08.09.2019 Mönchengladbach';
UPDATE veranstaltungen SET name = 'Blaulichtlauf' WHERE kuerzel = '14.08.2019 Gelsenkirchen';
UPDATE veranstaltungen SET name = 'Deutsche Seniorenmeisterschaften (2/2)' WHERE kuerzel = '13.07.2019 Leinefelde-Worbis';
UPDATE veranstaltungen SET name = 'Deutsche Seniorenmeisterschaften (1/2)' WHERE kuerzel = '12.07.2019 Leinefelde-Worbis';
UPDATE veranstaltungen SET name = 'Sommerlauf' WHERE kuerzel = '06.07.2019 Bösinghoven';
UPDATE veranstaltungen SET name = 'Offene NR-Meisterschaften' WHERE kuerzel = '30.06.2019 Kevelaer';
UPDATE veranstaltungen SET name = 'Himmelgeister Brückenlauf' WHERE kuerzel = '29.06.2019 Düsseldorf';
UPDATE veranstaltungen SET name = 'NEW-Citylauf' WHERE kuerzel = '16.06.2019 Erkelenz';
UPDATE veranstaltungen SET name = 'Altstadtlauf' WHERE kuerzel = '02.06.2019 Kempen';
UPDATE veranstaltungen SET name = 'Brunnenlauf' WHERE kuerzel = '29.05.2019 Sonsbeck';
UPDATE veranstaltungen SET name = 'Rahser-Run' WHERE kuerzel = '19.05.2019 Viersen';
UPDATE veranstaltungen SET name = 'Vivawest-Marathon' WHERE kuerzel = '19.05.2019 Gelsenkirchen';
UPDATE veranstaltungen SET name = 'ART Läuferabend' WHERE kuerzel = '15.05.2019 Düsseldorf';
UPDATE veranstaltungen SET name = 'Bahneröffnung' WHERE kuerzel = '08.05.2019 Oedt';
UPDATE veranstaltungen SET name = 'NRW-Meisterschaft' WHERE kuerzel = '04.05.2019 Neuss';
UPDATE veranstaltungen SET name = 'Sprint in den Mai' WHERE kuerzel = '01.05.2019 Viersen';
UPDATE veranstaltungen SET name = 'Apfelblütenlauf' WHERE kuerzel = '28.04.2019 Vorst';
UPDATE veranstaltungen SET name = 'Winterlauf-Serie (3/3)' WHERE kuerzel = '23.03.2019 Duisburg';
UPDATE veranstaltungen SET name = 'Karnevalslauf' WHERE kuerzel = '02.03.2019 MG-Hardt';
UPDATE veranstaltungen SET name = 'Winterlauf-Serie (2/3)' WHERE kuerzel = '23.02.2019 Duisburg';
UPDATE veranstaltungen SET name = 'Winterlauf-Serie (1/3)' WHERE kuerzel = '26.01.2019 Duisburg';
UPDATE veranstaltungen SET name = 'Waldlauf' WHERE kuerzel = '19.01.2019 Hinsbeck';
UPDATE veranstaltungen SET name = 'NRW Meisterschaften Halle (2/2)' WHERE kuerzel = '12.01.2019 Düsseldorf';
UPDATE veranstaltungen SET name = 'LLG Kevelaer-Marathon' WHERE kuerzel = '06.01.2019 Kevelaer';
UPDATE veranstaltungen SET name = 'NRW Meisterschaften Halle (1/2)' WHERE kuerzel = '06.01.2019 Düsseldorf';
UPDATE veranstaltungen SET name = 'Mainova-Marathon' WHERE kuerzel = '28.10.2018 Frankfurt';
UPDATE veranstaltungen SET name = 'Winterlaufserie (3/3)' WHERE kuerzel = '29.03.2008 Duisburg';
UPDATE veranstaltungen SET name = 'Winterlaufserie (2/3)' WHERE kuerzel = '01.03.2008 Duisburg';
UPDATE veranstaltungen SET name = 'Nettetaler Halbmarathon' WHERE kuerzel = '28.10.2006 Nettetal';
UPDATE veranstaltungen SET name = 'Winterlaufserie (3/3)' WHERE kuerzel = '18.03.2006 Nettetal';
UPDATE veranstaltungen SET name = 'Nettetaler Halbmarathon' WHERE kuerzel = '31.10.1998 Nettetal';
UPDATE veranstaltungen SET name = 'Winterlaufserie (3/3)' WHERE kuerzel = '14.03.1998 Nettetal';
UPDATE veranstaltungen SET name = 'Winterlaufserie (3/3)' WHERE kuerzel = '16.03.1996 Nettetal';
UPDATE veranstaltungen SET name = 'Winterlaufserie (1/3)' WHERE kuerzel = '20.01.1996 Nettetal';
UPDATE veranstaltungen SET name = 'Winterlaufserie (3/3)' WHERE kuerzel = '15.04.1995 Nettetal';
UPDATE veranstaltungen SET name = 'Winterlaufserie (2/3)' WHERE kuerzel = '01.04.1995 Nettetal';
UPDATE veranstaltungen SET name = 'Winterlaufserie (3/3)' WHERE kuerzel = '16.03.1991 Nettetal';
UPDATE veranstaltungen SET name = 'Winterlaufserie (1/3)' WHERE kuerzel = '26.01.1991 Nettetal';